#!/bin/sh

case `lsb_release -ds` in
  Ubuntu*)
    apt-get install -y \
      bsdutils \
      libxcb-icccm4-dev \
      libxcb-ewmh-dev \
      libxcb-keysyms1-dev \
      libfontconfig1-dev \
      libfreetype6-dev \
      libegl1-mesa-dev \
      libharfbuzz-dev \
      ragel
    ;;
  *)
    echo "Please contribute the commands to install the deps"
    echo "For `lsb_release -ds`"
    ;;
esac
