#!/bin/bash

# Centos may not have lsb_release installed
if test -e /etc/centos-release || test -e /etc/fedora-release; then
  if test -x /bin/dnf ; then
    YUM=dnf
  else
    YUM=yum
  fi
  $YUM install -y \
    make \
    gcc \
    gcc-c++ \
    dbus-devel \
    fontconfig-devel \
    openssl-devel \
    python3 \
    libxcb-devel \
    libxkbcommon-devel \
    libxkbcommon-x11-devel \
    wayland-devel \
    mesa-libEGL-devel \
    xcb-util-keysyms-devel \
    xcb-util-wm-devel \
    rpm-build \
    redhat-lsb-core
  exit $?
fi

if test -e /etc/debian_version ; then
  apt-get install -y \
    bsdutils \
    cmake \
    fakeroot \
    gcc \
    g++ \
    libdbus-1-dev \
    libegl1-mesa-dev \
    libssl-dev \
    libfontconfig1-dev \
    libwayland-dev \
    libx11-xcb-dev \
    libxcb-ewmh-dev \
    libxcb-icccm4-dev \
    libxcb-keysyms1-dev \
    libxcb-shm0-dev \
    libxcb-xkb-dev \
    libxkbcommon-dev \
    libxkbcommon-x11-dev \
    lsb-release \
    python3 \
    xdg-utils \
    xorg-dev
  exit $?
fi

if test -e /etc/arch-release ; then
  pacman -S --noconfirm --needed
    'cargo' \
    'cmake' \
    'dbus' \
    'fontconfig' \
    'git' \
    'hicolor-icon-theme' \
    'libx11' \
    'libxkbcommon-x11' \
    'pkgconf' \
    'python3' \
    'rust' \
    'wayland' \
    'xcb-util-keysyms' \
    'xcb-util-wm'
  exit $?
fi

case $OSTYPE in
  darwin*|msys)
    exit 0
  ;;
  freebsd*)
    pkg install -y \
      cmake \
      curl \
      dbus \
      egl-wayland \
      expat \
      fontconfig \
      gcc \
      gettext \
      git \
      gmake \
      libxcb \
      libxkbcommon \
      mesa-devel \
      openssl \
      p5-ExtUtils-MakeMaker \
      perl5 \
      pkgconf \
      python3 \
      rust \
      wayland \
      xcb-util-keysyms \
      xcb-util-wm \
      z \
      zip
    exit $?
    ;;
  *)
    echo "Please contribute the commands to install the deps"
    echo "For `lsb_release -ds`"
    exit 1
  ;;
esac
