#!/bin/bash
# Replays a recorded session
TRANSCRIPT="$1"

if test -z "$TRANSCRIPT" -o ! -f "$TRANSCRIPT" ; then
  echo "usage: wt-replay TRANSCRIPT.tgz"
  exit 1
fi

WHERE=`mktemp -d`
tar xzf "$TRANSCRIPT" -C $WHERE

echo "--- Starting replay ---"
case $OSTYPE in
  darwin*)
    script -p $WHERE/*.typescript
    ;;
  linux*)
    scriptreplay $WHERE/*.timing $WHERE/*.typescript
    ;;
esac
echo "--- replay complete ---"

