#!/bin/bash
# Runs wezterm using `script` to record a session with timing information

NOW=`date -u +%Y%m%d%H%M%S`
echo $NOW
PATH=$PWD/target/release:$PATH

case $OSTYPE in
  darwin*)
    wezterm start -- script -r $PWD/$NOW.typescript
    tar -cz -f $NOW.tgz $NOW.typescript
    ;;

  linux*)
    wezterm start -- script -t$NOW.timing $NOW.typescript
    tar -cz --remove-files -f $NOW.tgz $NOW.timing $NOW.typescript
    ;;
esac

echo "Transcript recorded in $NOW.tgz"
